#!/opt/homebrew/bin/bash
# L-832C tables — GENERATED FROM THE ARM ARTIFACTS. Every value is read out of an
# ARM.txt or ledger.tsv. Nothing here is typed by hand.
set -uo pipefail
A="${1:-/Users/ckriech/projects/clemens33/ae-rust/docs/migration/evidence/l-artifacts/L-832C}"
f() { local v; v="$(grep -m1 "^$2" "$1" 2>/dev/null | cut -f2)"; printf '%s' "${v:--}"; }

printf '# L-832C tables — GENERATED by _harness/c832-mktables.sh. CAPTURE ONLY.\n\n'

printf '## TABLE 1 — the post-crash identity tuple per cut, and whether the sources disagree\n'
printf '##            (one row per arm; the tuple is a property of the CUT, so rows for the\n'
printf '##             same cut are independent runs of the same construction)\n'
printf '%-30s %-7s %-12s %-16s %-16s %-16s %s\n' ARM CUT CONSUMER tmux_names dir_names meta_sessions disagree
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; a="$d/ARM.txt"; [[ -f "$a" ]] || continue
  printf '%-30s %-7s %-12s %-16s %-16s %-16s %s\n' "$n" "$(f "$a" cut)" "$(f "$a" consumer)" \
    "$(f "$a" postcrash.tmux_names)" "$(f "$a" postcrash.dir_names)" "$(f "$a" postcrash.meta_sessions)" \
    "$(f "$a" postcrash.sources_disagree)"
done

printf '\n## TABLE 2 — preconditions and the fresh-process consumer\n'
printf '%-30s %-14s %-11s %-46s %s\n' ARM precondition rename_rc consumer_rcs ARM_INVALID
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; a="$d/ARM.txt"; [[ -f "$a" ]] || continue
  printf '%-30s %-14s %-11s %-46s %s\n' "$n" "$(f "$a" precondition_met)" "$(f "$a" rename_rc)" \
    "$(f "$a" consumer_rcs)" "$( [[ -f "$d/ARM-INVALID.txt" ]] && echo YES || echo no )"
done

printf '\n## TABLE 3 — mutation after the fresh-process consumer, in manifest lines changed\n'
printf '##            clone = the consumer own post-crash clone; origin = the crashed state itself\n'
printf '%-30s %-12s %-16s %s\n' ARM consumer clone_changed origin_changed
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; a="$d/ARM.txt"; [[ -f "$a" ]] || continue
  printf '%-30s %-12s %-16s %s\n' "$n" "$(f "$a" consumer)" \
    "$(f "$a" clone_manifest_changed_lines)" "$(f "$a" origin_manifest_changed_lines)"
done

printf '\n## TABLE 4 — the stable session id per state directory, post-crash\n'
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; t="$d/tuple.3post-crash.row"; [[ -f "$t" ]] || continue
  printf '  %-30s session_ids(8): %s\n' "$n" "$(grep -m1 '^session_ids' "$t" | cut -f2)"
done
