#!/opt/homebrew/bin/bash
# L-DISCRIM tables — GENERATED FROM THE ARM ARTIFACTS. Every value is read out of an
# ARM.txt or ledger.tsv. Nothing here is typed by hand.
set -uo pipefail
A="${1:-/Users/ckriech/projects/clemens33/ae-rust/docs/migration/evidence/l-artifacts/L-DISCRIM}"
f() { local v; v="$(grep -m1 "^$2" "$1" 2>/dev/null | cut -f2)"; printf '%s' "${v:--}"; }

printf '# L-DISCRIM tables — GENERATED by _harness/discrim-mktables.sh. CAPTURE ONLY.\n\n'
printf '## TABLE 1 — every arm, its ability-to-fail control, and whether it could fail\n'
printf '%-34s %-13s %-13s %s\n' ARM ARM_INVALID PATCH ability_to_fail_control
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; a="$d/ARM.txt"; [[ -f "$a" ]] || continue
  case "$n" in
    D1*) ctl="control_replacement_accepted=$(f "$a" control_replacement_accepted | cut -c1-3)" ;;
    D2*) ctl="counts non-zero AND distinct: $(f "$a" parent_counts)" ;;
    D3*) ctl="recorder proven live by direct invocation: $(f "$a" recorder.direct.invocations) call(s)" ;;
    D4*) ctl="leaked SIG_IGN detected: $(f "$a" leaked_ign_detected)" ;;
    D5a*) ctl="sampler rate recorded: $(f "$a" sampler_rate)" ;;
    D5b*) ctl="held at a barrier, no race to lose" ;;
    *) ctl="-" ;;
  esac
  printf '%-34s %-13s %-13s %s\n' "$n" \
    "$( [[ -f "$d/ARM-INVALID.txt" ]] && echo YES || echo no )" \
    "$(f "$a" hook_patch_version | cut -c1-12)" "$ctl"
done

printf '\n## TABLE 2 — D1 and D2, the lineage tuples read BY EXACT KEY\n'
printf '%-34s %-22s %-24s %s\n' ARM parent_counts other observed
for d in "$A"/arms/D1* "$A"/arms/D2*; do
  [[ -d "$d" ]] || continue
  n="$(basename "$d")"; a="$d/ARM.txt"
  case "$n" in
    D1*) printf '%-34s %-22s %-24s %s\n' "$n" "$(f "$a" parent_counts)" \
           "replacement: $(f "$a" replacement_counts)" \
           "child recorded handover=$(f "$a" child_recorded_handover) pending=$(f "$a" child_recorded_pending)" ;;
    D2*) printf '%-34s %-22s %-24s %s\n' "$n" "$(f "$a" parent_counts)" \
           "after_from: $(f "$a" after_from)" "after_resume: $(f "$a" after_resume)" ;;
  esac
done

printf '\n## TABLE 3 — D3 reachability, per gate\n'
for d in "$A"/arms/D3*; do
  [[ -d "$d" ]] || continue
  a="$d/ARM.txt"
  printf '  recorder proven live by a DIRECT rsync invocation : %s call(s)\n' "$(f "$a" recorder.direct.invocations)"
  printf '  ae valid-name path, ssh invocations               : %s\n' "$(f "$a" ae.valid_name.ssh.invocations)"
  printf '  ae valid-name path, rsync invocations             : %s\n' "$(f "$a" ae.valid_name.rsync.invocations)"
  printf '  ae valid-name path rc                             : %s\n' "$(f "$a" ae.valid_name.rc)"
  printf '  canary available on the ae path                   : %s\n' "$(f "$a" canary_available)"
done

printf '\n## TABLE 4 — D4 dispositions (from the arm own generated disposition-table.txt)\n'
for d in "$A"/arms/D4*; do
  [[ -f "$d/disposition-table.txt" ]] && sed 's/^/  /' "$d/disposition-table.txt"
done

printf '\n## TABLE 5 — D5, caught alive or not\n'
printf '%-34s %-14s %-16s %s\n' ARM caught_alive supervisor_pid method
for d in "$A"/arms/D5*; do
  [[ -d "$d" ]] || continue
  n="$(basename "$d")"; a="$d/ARM.txt"
  if [[ "$n" == D5a* ]]; then
    printf '%-34s %-14s %-16s %s\n' "$n" "$(f "$a" caught_alive)" "$(f "$a" supervisor_first_pid)" "pgrep sampler, no sleep — $(f "$a" sampler_rate)"
  else
    printf '%-34s %-14s %-16s %s\n' "$n" "$(f "$a" caught_alive)" "$(f "$a" supervisor_pid_at_barrier)" "held at b_stop_supervisor_singular_entry"
  fi
done
