
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.base64]]
version = "0.23.1"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.4.4"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.11"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.34"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.35"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.15"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ureq]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.ureq-proto]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.utf8-zero]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.9.0"
criteria = "safe-to-deploy"
