#!/usr/bin/env python3
"""GENERATOR — writes the corpus freeze. Run deliberately, never by a gate.

A GATE READS, A GENERATOR WRITES, AND THEY ARE DIFFERENT PROGRAMS RUN AT DIFFERENT
TIMES. This file only writes; `verify-corpus.py` only reads. They are kept apart
because a gate that regenerates the table it reports on overwrites the drift it
exists to detect — "regenerate" then silently means "repair".

Usage:  ./freeze-corpus.py            # write CORPUS-MANIFEST.tsv + FREEZE.txt
"""
import hashlib, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "batch-c-artifacts"))
MANIFEST = os.path.join(HERE, "CORPUS-MANIFEST.tsv")
FREEZE = os.path.join(HERE, "FREEZE.txt")
HDR = ["role", "sha256", "bytes", "path"]

def role(rel):
    """Roles are DERIVED from path shape, not hand-assigned per file."""
    if rel.startswith("twd-precursor/"):
        return "OUT-OF-SCOPE"          # P4 precursor material; frozen, not consumed by P1 parity
    if rel.startswith("templates/"):
        return "FIXTURE"               # the bytes a parity run materialises
    if rel.startswith("hook-patch/"):
        return "PROVENANCE"
    base = os.path.basename(rel)
    if "/out/" in rel:
        return "EXPECTED"              # captured rc/stdout/stderr/tmuxtrace
    if base in ("consumers.tsv", "case.txt", "env.txt"):
        return "INVOCATION"            # argv, rc, environment, template binding
    if base == "manifest.before.tsv":
        return "FIXTURE"
    if base in ("manifest.after.tsv", "manifest.diff.txt", "tmux.before.txt", "tmux.after.txt"):
        return "NO-MUTATION"           # the read-side must not change the tree
    return "PROVENANCE"

def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()

def walk():
    rows = []
    for dirpath, dirnames, filenames in os.walk(SRC):
        dirnames.sort()
        for fn in sorted(filenames):
            p = os.path.join(dirpath, fn)
            rel = os.path.relpath(p, SRC)
            rows.append((role(rel), sha256(p), str(os.path.getsize(p)), rel))
    rows.sort(key=lambda r: r[3])
    return rows

def root_digest(rows):
    """One digest over the whole listing: any change to any listed file, and any
    addition or removal, moves it."""
    h = hashlib.sha256()
    for r in rows:
        h.update(("\t".join(r) + "\n").encode())
    return h.hexdigest()

def main():
    rows = walk()
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write("\t".join(HDR) + "\n")
        for r in rows:
            f.write("\t".join(r) + "\n")
    commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=HERE,
                            capture_output=True, text=True).stdout.strip()
    counts = {}
    for r in rows:
        counts[r[0]] = counts.get(r[0], 0) + 1
    with open(FREEZE, "w", encoding="utf-8") as f:
        f.write("# Corpus freeze record — generated by freeze-corpus.py\n")
        f.write("# The corpus is a NAMED, HASH-PINNED VIEW over already-accepted artifacts.\n")
        f.write("# The bytes are not copied; this record is what makes them a corpus.\n\n")
        f.write("source\tdocs/migration/evidence/batch-c-artifacts\n")
        f.write("frozen_at_commit\t%s\n" % commit)
        f.write("files\t%d\n" % len(rows))
        f.write("root_digest\t%s\n" % root_digest(rows))
        for k in sorted(counts):
            f.write("role.%s\t%d\n" % (k, counts[k]))
    print("wrote %s (%d files) and %s" % (MANIFEST, len(rows), FREEZE))
    print("root_digest %s" % root_digest(rows))

if __name__ == "__main__":
    main()
