#!/usr/bin/env python3
"""Verify every `ae:NNNN` citation in a document against the frozen source, and PIN it.

Why this exists: the steward citations in this census were wrong by a constant 8 because
they were transcribed from a WINDOWED grep — offsets inside a window written down as
absolute line numbers — while the document claimed exact verification. A line number is a
claim; the line's text is the evidence. This tool fetches each cited line from
`git show <commit>:ae` and writes a generated pin file so a seat reads source text rather
than trusting arithmetic.

It cannot know what a citation MEANT to point at, so it does not try. It reports:
  - citations whose line does not exist,
  - citations landing on a blank line or a closing brace (the classic off-by-N landing),
  - and it emits every cited line verbatim for review.

usage: check-citations.py <doc.md> [<doc.md> ...] --commit <sha> --repo <path> --out <pins.md>
"""
import re, subprocess, sys

args = sys.argv[1:]
if not args or "--commit" not in args:
    sys.stderr.write("usage: check-citations.py <doc.md> ... --commit <sha> --repo <path> --out <pins.md>\n")
    sys.exit(2)
def opt(name, default=None):
    return args[args.index(name) + 1] if name in args else default
commit, repo, out = opt("--commit"), opt("--repo", "."), opt("--out")
docs = [a for a in args if a.endswith(".md") and a != out]

src = subprocess.run(["git", "-C", repo, "show", f"{commit}:ae"],
                     capture_output=True, text=True, check=True).stdout.split("\n")

rows, bad = [], []
for doc in docs:
    text = open(doc, encoding="utf-8").read()
    for m in re.finditer(r"ae:(\d+)(?:-(\d+))?", text):
        first = int(m.group(1))
        ends = [(first, "start")] + ([(int(m.group(2)), "end")] if m.group(2) else [])
        for n, kind in ends:
            if n < 1 or n > len(src):
                bad.append((doc, n, "line does not exist in the frozen source")); continue
            line = src[n - 1]
            # A RANGE END landing on `}` is a function span, which is correct. Only a
            # citation that POINTS AT something — a single line, or a range's start — is
            # suspicious when it lands on a brace or a blank.
            if kind == "start":
                if not line.strip():
                    bad.append((doc, n, "cited line is BLANK"))
                elif line.strip() == "}":
                    bad.append((doc, n, "cited line is a bare closing brace"))
            rows.append((doc.split("/")[-1], n, line.rstrip()))

rows.sort(key=lambda r: (r[0], r[1]))
if out:
    L = [f"# Citation pins — every `ae:NNNN` in the Batch H documents, resolved at {commit}",
         "",
         "GENERATED by `batch-h-tools/check-citations.py`. Each row is the cited line's own",
         "text, fetched from `git show` — so a citation is checkable against source rather",
         "than trusted as arithmetic. A line number is a claim; the line is the evidence.",
         "", "| document | line | source text |", "|---|---|---|"]
    for d, n, t in rows:
        L.append(f"| {d} | ae:{n} | `{t.strip().replace('|', chr(92)+'|')[:110]}` |")
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")

print(f"citations_pinned={len(rows)} suspicious={len(bad)}")
for b in bad:
    print(f"  SUSPICIOUS {b[0]}:{b[1]} — {b[2]}")
sys.exit(1 if bad else 0)
