#!/usr/bin/env python3
"""Verify every `ae:NNNN` citation in a document against the frozen source, and PIN it.

Why this exists: the steward citations in this census were wrong by a constant 8 because
they were transcribed from a WINDOWED grep — offsets inside a window written down as
absolute line numbers — while the document claimed exact verification. A line number is a
claim; the line's text is the evidence. This tool fetches each cited line from
`git show <commit>:ae` and writes a generated pin file so a seat reads source text rather
than trusting arithmetic.

It cannot know what a citation MEANT to point at, so it does not try. It reports:
  - citations whose line does not exist,
  - citations landing on a blank line or a closing brace (the classic off-by-N landing),
  - and it emits every cited line verbatim for review.

For a RANGE (`ae:100-140`) it pins the ENDPOINTS, not every line between them — the file is
named endpoint pins for that reason, and a claim that a seat "sees the cited range" would be
false of it.

`--check` regenerates to a temp file and compares against the committed one, so a stale
committed artifact is a failure rather than a document nobody re-ran. `--redproof` runs the
failure injections.

usage: check-citations.py <doc.md> [...] --commit <sha> --repo <path> [--out <pins.md>] [--check] [--redproof]
"""
import os, re, subprocess, sys, tempfile

args = sys.argv[1:]
if not args or "--commit" not in args:
    sys.stderr.write("usage: check-citations.py <doc.md> ... --commit <sha> --repo <path> --out <pins.md>\n")
    sys.exit(2)
def opt(name, default=None):
    return args[args.index(name) + 1] if name in args else default
commit, repo, out = opt("--commit"), opt("--repo", "."), opt("--out")
docs = [a for a in args if a.endswith(".md") and a != out]

src = subprocess.run(["git", "-C", repo, "show", f"{commit}:ae"],
                     capture_output=True, text=True, check=True).stdout.split("\n")

rows, bad = [], []
for doc in docs:
    text = open(doc, encoding="utf-8").read()
    for m in re.finditer(r"ae:(\d+)(?:-(\d+))?", text):
        first = int(m.group(1))
        ends = [(first, "start")] + ([(int(m.group(2)), "end")] if m.group(2) else [])
        for n, kind in ends:
            if n < 1 or n > len(src):
                bad.append((doc, n, "line does not exist in the frozen source")); continue
            line = src[n - 1]
            # A RANGE END landing on `}` is a function span, which is correct. Only a
            # citation that POINTS AT something — a single line, or a range's start — is
            # suspicious when it lands on a brace or a blank.
            if kind == "start":
                if not line.strip():
                    bad.append((doc, n, "cited line is BLANK"))
                elif line.strip() == "}":
                    bad.append((doc, n, "cited line is a bare closing brace"))
            rows.append((doc.split("/")[-1], n, line.rstrip()))

rows.sort(key=lambda r: (r[0], r[1]))

# The expected artifact is built IN MEMORY first. The previous version wrote the file and
# then "compared" it against the same text it had just written, so --check could never fail
# — it silently REPAIRED a stale artifact and returned 0. Proven live by a seat: an empty
# file passed --check and came back populated.
L = [f"# Citation ENDPOINT pins — every `ae:NNNN` in the Batch H documents, resolved at {commit}",
     "",
     "GENERATED by `batch-h-tools/check-citations.py`. Each row is the cited line's own",
     "text, fetched from `git show` — so a citation is checkable against source rather",
     "than trusted as arithmetic. A line number is a claim; the line is the evidence.",
     "",
     "ENDPOINTS ONLY: a range pins its first and last line, not the lines between them.",
     "And a pin proves a citation RESOLVES — never that it is the RIGHT line for the",
     "claim beside it. A confident citation on a wrong-but-plausible line passes clean;",
     "the +8 steward citations this tool was built after would have passed it, and so did",
     "three semantically wrong SC-211o citations that a seat caught by reading the source.",
     "It makes a seat's reading cheap; it does not perform the reading.",
     "", "| document | line | source text |", "|---|---|---|"]
for d, n, t in rows:
    L.append(f"| {d} | ae:{n} | `{t.strip().replace('|', chr(92)+'|')[:110]}` |")
expected = "\n".join(L) + "\n"

check = "--check" in args
if check:
    if not out:
        sys.stderr.write("--check requires --out naming the committed artifact\n")
        sys.exit(2)
    try:
        committed = open(out, encoding="utf-8").read()
    except OSError:
        committed = None
    if committed is None:
        bad.append((out, 0, "committed pin file is MISSING"))
    elif committed != expected:
        bad.append((out, 0, "committed pin file is STALE — regeneration differs"))
elif out:
    open(out, "w", encoding="utf-8").write(expected)

if "--redproof" in args:
    import tempfile, os
    print("## red-proof — each injection must be CAUGHT")
    def arm(text, label):
        d = os.path.join(tempfile.mkdtemp(), "probe.md")
        open(d, "w", encoding="utf-8").write(text)
        r = subprocess.run([sys.executable, __file__, d, "--commit", commit, "--repo", repo],
                           capture_output=True, text=True)
        caught = r.returncode != 0
        print(f"  {label:34s} caught={'YES' if caught else 'NO'}")
        return caught
    blank = next((i + 1 for i, l in enumerate(src) if not l.strip()), 3)
    brace = next((i + 1 for i, l in enumerate(src) if l.strip() == "}"), 4)
    ok = True
    # Vacuity control: a document whose citations are all valid must report NOT caught.
    # Without it, a red-proof set that never says NO is indistinguishable from a constant.
    null_ok = not arm("ae:16740\n", "NULL arm (must be NO)")
    if not null_ok:
        bad.append(("redproof", 0, "the citation harness reports caught on a VALID citation"))
    ok &= null_ok
    ok &= arm(f"ae:{len(src) + 5000}\n", "citation past end of file")
    ok &= arm(f"ae:{blank}\n", "citation on a blank line")
    ok &= arm(f"ae:{brace}\n", "citation on a bare closing brace")

    # STALE-OUTPUT arm: --check against an artifact that is not what regeneration produces
    # must FAIL and must NOT repair it. This is the arm whose absence let --check pass on
    # an empty file.
    d = os.path.join(tempfile.mkdtemp(), "doc.md"); o = os.path.join(os.path.dirname(d), "pins.md")
    open(d, "w", encoding="utf-8").write("ae:16740\n")
    open(o, "w", encoding="utf-8").write("")          # deliberately stale (empty)
    r = subprocess.run([sys.executable, __file__, d, "--commit", commit, "--repo", repo,
                        "--out", o, "--check"], capture_output=True, text=True)
    untouched = open(o, encoding="utf-8").read() == ""
    caught = r.returncode != 0 and untouched
    print(f"  {'stale committed pin file':34s} caught={'YES' if caught else 'NO'}"
          f"{'' if untouched else ' (and it was OVERWRITTEN)'}")
    ok &= caught
    if not ok:
        bad.append(("redproof", 0, "a red arm was not caught"))

print(f"citations_pinned={len(rows)} suspicious={len(bad)}")
for b in bad:
    print(f"  SUSPICIOUS {b[0]}:{b[1]} — {b[2]}")
sys.exit(1 if bad else 0)
