#!/usr/bin/env python3
"""Derive the BRIEF-FACING input list from the SEAT-FACING argument census.

THE DROP IS COLUMNAR, NOT LEXICAL. The census is a markdown table whose first column is
the input and whose remaining columns name what the input reaches and how it is classed.
This generator keeps column 1 and discards every other column outright, so no word from an
outcome column can reach the brief whatever its spelling. A vocabulary filter would have to
enumerate the leak words, and an enumeration is beaten by the first word nobody listed.

Spellings separated by " / " are EXPANDED into separate entries: a brief that groups them
would let one chosen spelling stand for the group, and spelling parity is exactly what
several of these rows are about.

usage: derive-input-list.py <census.md> <out.md>
"""
import re, sys

src, out = sys.argv[1], sys.argv[2]
lines = open(src, encoding="utf-8").read().split("\n")

HEAD = ["# Batch H — executor input list (BRIEF-FACING)", "",
        "GENERATED by `batch-h-tools/derive-input-list.py` from the seat-facing argument",
        "census. Do not hand-edit — the checker regenerates it and compares byte for byte.",
        "",
        "Only the census's INPUT column survives. What each input reaches, and how the",
        "incumbent source classes it, are separate columns and are dropped whole — so the",
        "brief cannot carry an outcome label, whatever that label is called. Spellings are",
        "expanded, so every one is invoked as its own capture.",
        "",
        "A row that names a fixture property rather than an argv is a fixture fact to",
        "construct, not an argument to pass.", ""]

body, keep, seen = [], False, set()
for ln in lines:
    if ln.startswith("## ") or ln.startswith("### "):
        title = re.sub(r"\s+—.*$", "", ln)          # drop the heading tail
        title = re.sub(r"^#+\s*", "", title)          # drop the heading marker
        title = re.sub(r"\s*\(ae:[^)]*\)", "", title)  # drop the source location
        low = title.lower()
        if any(k in low for k in ("argument census", "row -> input-class", "row ->")):
            keep = False; continue
        keep = True
        body += ["", f"## Surface: {title.strip()}", ""]
        continue
    if not keep or not ln.startswith("|"):
        continue
    cells = [c.strip() for c in ln.strip("|").split("|")]
    inp = cells[0] if cells else ""
    if not inp or inp.lower().startswith("input") or set(inp) <= set("-: "):
        continue
    for part in [p.strip() for p in inp.split(" / ")]:
        if part and (title, part) not in seen:
            seen.add((title, part)); body.append(f"- {part}")

txt = "\n".join(HEAD + body) + "\n"
open(out, "w", encoding="utf-8").write(txt)
print(f"{len(seen)} input entries written to {out}")
