#!/usr/bin/env python3
"""Derive the BRIEF-FACING input list from the SEAT-FACING argument census.

THE DROP IS COLUMNAR, NOT LEXICAL. The census is a markdown table whose first column is
the input and whose remaining columns name what the input reaches and how it is classed.
This generator keeps column 1 and discards every other column outright, so no word from an
outcome column can reach the brief whatever its spelling. A vocabulary filter would have to
enumerate the leak words, and an enumeration is beaten by the first word nobody listed.

Spellings separated by "/" are EXPANDED into separate entries: a brief that groups them
would let one chosen spelling stand for the group, and spelling parity is exactly what
several of these rows are about.

OWNERSHIP IS A TYPED FIELD, APPLIED BEFORE THE DROP. Every in-scope census table carries a
trailing Scope column valued IN or OOB:<owner>; this generator REQUIRES it, validates the
value and the row's column count, and excludes OOB rows from the executor brief. An earlier
version looked for the substring OUT-OF-BATCH in any cell, which let prose change scope by
accident and made a missing scope silent. Duplicate (surface, input) records and conflicting
ownership are FAILURES, detected BEFORE the scope filter so the filter cannot erase them.

usage: derive-input-list.py <census.md> <out.md>
"""
import re, sys

if len(sys.argv) < 3:
    sys.stderr.write("usage: derive-input-list.py <census.md> <out.md>\n")
    sys.exit(2)
src, out = sys.argv[1], sys.argv[2]
lines = open(src, encoding="utf-8").read().split("\n")

HEAD = ["# Batch H — executor input list (BRIEF-FACING)", "",
        "GENERATED by `batch-h-tools/derive-input-list.py` from the seat-facing argument",
        "census. Do not hand-edit — the checker regenerates it and compares byte for byte.",
        "",
        "Only the census's INPUT column survives. What each input reaches, and how the",
        "incumbent source classes it, are separate columns and are dropped whole — so the",
        "brief cannot carry an outcome label, whatever that label is called. Spellings are",
        "expanded, so every one is invoked as its own capture.",
        "",
        "A row that names a fixture property rather than an argv is a fixture fact to",
        "construct, not an argument to pass.", ""]

def split_spellings(cell):
    """Expand alternative spellings into separate entries.

    Splits on a slash that separates two code spans or bare tokens, with or without
    surrounding spaces — `mine`/`inbox`/`all` and `--attach` / `--switch` are the same
    construction and an executor list that expanded only one of them would keep the
    promise for half the rows.
    """
    cell = cell.strip()
    # A spelling list is the WHOLE cell being alternatives — `mine` / `inbox` / `all`,
    # `--attach` / `--switch`. Anything else stays whole: "malformed / missing first-line
    # id" is one input whose description contains a slash, and an earlier, looser rule
    # split it into "malformed" and "missing first-line id", inventing an input and
    # dropping the real one. The rule is anchored end to end for exactly that reason.
    part = r"(?:`[^`]+`|[A-Za-z0-9_.:+-]+)"
    if re.fullmatch(rf"{part}(?:\s*/\s*{part})+", cell):
        return [x.strip() for x in re.split(r"\s*/\s*", cell)]
    return [cell]

SCOPE_RE = re.compile(r"IN|OOB:[A-Za-z0-9_.\-]+")
body, keep, seen, dupes = [], False, set(), []
all_keys, errors, ncols, scope_idx = {}, [], {}, None
for ln in lines:
    if ln.startswith("## ") or ln.startswith("### "):
        title = re.sub(r"\s+—.*$", "", ln)          # drop the heading tail
        title = re.sub(r"^#+\s*", "", title)          # drop the heading marker
        title = re.sub(r"\s*\(ae:[^)]*\)", "", title)  # drop the source location
        low = title.lower()
        # A section marked (seat-only) carries source-derived material that is not an
        # input at all — a family comparison, a mapping table. It is skipped by the
        # SECTION, not by inspecting its rows: the same columnar principle one level up.
        if "(seat-only)" in low or any(k in low for k in ("argument census", "row -> input-class", "row ->")):
            keep = False; continue
        keep = True
        body += ["", f"## Surface: {title.strip()}", ""]
        continue
    if not keep or not ln.startswith("|"):
        continue
    cells = [c.strip() for c in ln.strip("|").split("|")]
    inp = cells[0] if cells else ""
    if not inp or set(inp) <= set("-: "):
        continue
    if inp.lower().startswith("input"):
        # header: the Scope column is REQUIRED and its position is taken from here, so a
        # table without one fails loudly instead of defaulting every row into scope.
        if not cells or cells[-1] != "Scope":
            errors.append(f"{title}: table header has no trailing Scope column")
            scope_idx = None
        else:
            scope_idx = len(cells) - 1
            ncols[title] = len(cells)
        continue
    if scope_idx is None:
        errors.append(f"{title}: data row before a valid header: {inp[:40]}")
        continue
    if len(cells) != ncols.get(title):
        errors.append(f"{title}: row has {len(cells)} columns, header has {ncols.get(title)}: {inp[:40]}")
        continue
    scope = cells[scope_idx]
    if not SCOPE_RE.fullmatch(scope):
        errors.append(f"{title}: scope value {scope!r} is not IN or OOB:<owner>: {inp[:40]}")
        continue
    for part in split_spellings(inp):
        key = (title, part)
        # Duplicate detection runs BEFORE the scope filter: two identical OOB rows, or an
        # IN row and a conflicting OOB row for the same input, would otherwise be erased by
        # the filter and never compared.
        if key in all_keys and all_keys[key] != scope:
            errors.append(f"{title}: conflicting scope for {part!r}: {all_keys[key]} vs {scope}")
        elif key in all_keys:
            dupes.append(key)
        all_keys[key] = scope
        if scope != "IN":
            continue
        seen.add(key)
        body.append(f"- {part}")

txt = "\n".join(HEAD + body) + "\n"
open(out, "w", encoding="utf-8").write(txt)
for d in dupes:
    print(f"DUPLICATE_CENSUS: {d}")
for e in errors:
    print(f"SCOPE_ERROR: {e}")
print(f"{len(seen)} input entries written to {out}")
sys.exit(2 if (dupes or errors) else 0)
