#!/opt/homebrew/bin/bash
# D02 / SC-1306d — request-scan reader vs reply writer. b0-design.md Design 3.
# Hook H_REQUEST_SCAN_COMPLETE, after `_ar_request_states` finishes its reversed scan and
# BEFORE row emission. At the barrier the controller appends ONE producer-harvested,
# identity-valid reply event. Capture the current invocation AND a clean rerun from the
# resulting clone. Controller-only twin.
source "$(dirname "$0")/dlib.sh"
ARMG=D
mkdir -p "$ADEST/$ARMG"
[[ -f "$ADEST/$ARMG/ledger.tsv" ]] || printf 'case\trows\tgroup\tmember\n' >"$ADEST/$ARMG/ledger.tsv"

append_reply() { # <ae-home> <sock>
    local aehome="$1" sess payload
    sess="$(ls "$aehome/sessions" | head -1)"
    payload="$aehome/_d02-controller-payload.reply.jsonl"
    { echo "mutation=append ONE producer-harvested, identity-valid reply event"
      echo "payload_file=_d02-controller-payload.reply.jsonl (carried inside the member itself)"
      echo "payload_sha256=$(sha "$payload") bytes=$(stat -f %z "$payload")"
      echo "payload_line: $(cat "$payload")"
      echo "utc=$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
      echo "events lines BEFORE: $(wc -l <"$aehome/sessions/$sess/events.jsonl" | tr -d ' ')"
      echo "events sha256 BEFORE: $(sha "$aehome/sessions/$sess/events.jsonl")"
    } >"$ACAP/controller-mutation.txt"
    cat "$payload" >>"$aehome/sessions/$sess/events.jsonl"
    { echo "events lines AFTER: $(wc -l <"$aehome/sessions/$sess/events.jsonl" | tr -d ' ')"
      echo "events sha256 AFTER: $(sha "$aehome/sessions/$sess/events.jsonl")"
    } >>"$ACAP/controller-mutation.txt"
    led controller-mutation "append=harvested reply line" "artifact_sha256=$(sha "$ACAP/controller-mutation.txt")"
}

d02_case() { # <case-id> <arm-kind>
    local cid="$1" kind="$2"
    local base="$AROOT/$ARMG/$cid"
    [[ -e "$base" ]] && chmod -R u+w "$base" 2>/dev/null; rm -rf "$base"; mkdir -p "$base/home"
    export ARM_TMUXTMP="$base/tmuxtmp"; mkdir -p "$ARM_TMUXTMP"
    case_open "$ARMG" "$cid" "$kind"
    led rows "rows=D02,SC-1306d" "template=D/d02-pending-with-harvested-reply" "design=b0-design.md Design 3"
    local aehome="$base/home/.ae"
    t_clone D d02-pending-with-harvested-reply "$aehome" rw || { led CLONE-FAILED; return 1; }
    local sess; sess="$(ls "$aehome/sessions" | head -1)"
    local cf exp
    cf="$(dir_fingerprint "$aehome")"; exp="$(grep '^fingerprint_pre_protection=' "$TSTORE/D/_meta/d02-pending-with-harvested-reply.txt" | cut -d= -f2-)"
    led clone-VERIFIED "clone_fingerprint=$cf" "expected=$exp" "matches=$( [[ "$cf" == "$exp" ]] && echo yes || echo no )"
    local sock="$base/live.sock"
    build_live_topology "$aehome" "$sock" "$sess"
    { echo "arm=$ARMG case=$cid arm_kind=$kind design=b0-design.md Design 3 (D02) rows=D02,SC-1306d"
      echo "template=D/d02-pending-with-harvested-reply clone_mode=rw session=$sess"
      echo "clone_fingerprint=$cf clone_fingerprint_matches_template=$( [[ "$cf" == "$exp" ]] && echo yes || echo no )"
      echo "hook=H_REQUEST_SCAN_COMPLETE (after the reversed scan, before row emission)"
      echo "unmodified_ae_sha256=$(sha "$FROZEN_AE") hooked_ae_sha256=$(sha "$HOOKED_AE") patch_sha256=$(sha "$HOOK_PATCH")"
      echo "consumer=the session's OWN generated requests helper (the frozen scan lives there)"
      echo "utc_start=$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"; } >"$ACAP/case.txt"
    case_env_record "$aehome" "$sock"
    env_tab_selfcheck || { led HARNESS-ABORT "reason=tab self-check"; return 1; }
    tmux_shim_equiv "$sock" "$sess" || { led HARNESS-ABORT "reason=tmux shim equivalence"; return 1; }
    if [[ "$kind" == barrier ]]; then
        hook_inactive_equiv "$aehome" "$sock" "$sess" || { led HARNESS-ABORT "reason=inactive-hook equivalence"; return 1; }
        cp "$HOOK_PATCH" "$ACAP/hook.patch"; led hook-patch-published "artifact_sha256=$(sha "$ACAP/hook.patch")"
        # `_ar_request_states` is emitted into the session's OWN generated `requests` helper
        # by declare -f, so the hook has to be in THAT helper, not only in `ae`. The clone's
        # helper set is regenerated by the HOOKED binary through the frozen refresh path,
        # and the pre-refresh helper is kept so the refreshed one can be proven equivalent
        # with the hook inactive before anything is captured through it.
        # The helper must be exercised IN PLACE: it sources _lib from its own directory,
        # so a copy in the capture dir cannot run at all. Capture the pre-refresh answer
        # first, then refresh, then capture the post-refresh answer from the same path.
        local a b ra rb
        a="$("$aehome/sessions/$sess/requests" all 2>&1)"; ra=$?
        cp "$aehome/sessions/$sess/requests" "$ACAP/requests.helper.pre-refresh"
        cp "$aehome/sessions/$sess/_lib" "$ACAP/_lib.pre-refresh"
        led helper-refresh-START "generator=hooked ae" "pre_requests_sha256=$(sha "$ACAP/requests.helper.pre-refresh")" \
            "pre_lib_sha256=$(sha "$ACAP/_lib.pre-refresh")"
        env -i "HOME=$(dirname "$aehome")" "AE_HOME=$aehome" \
            "PATH=${TMUX_SHIM_DIR}:${FLOCK_SHIM_DIR}:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin" \
            "TZ=UTC" "LANG=en_US.UTF-8" "LC_ALL=en_US.UTF-8" "TERM=xterm-256color" \
            "TMUX_TMPDIR=${ARM_TMUXTMP}" "AE_TMUX_SERVER=$sock" "AE_TMUX_SERVER_KIND=socket" \
            "AE_REAL_TMUX=/opt/homebrew/bin/tmux" "AE_REAL_FLOCK=/opt/homebrew/bin/flock" \
            "$HARNESS_BASH" "$HOOKED_AE" doctor --refresh "$sess" \
            >"$ACAP/out/helper-refresh.stdout" 2>"$ACAP/out/helper-refresh.stderr"
        local rrc=$?
        cp "$aehome/sessions/$sess/requests" "$ACAP/requests.helper.post-refresh"
        led helper-refresh-COMPLETE "rc=$rrc" "post_requests_sha256=$(sha "$ACAP/requests.helper.post-refresh")" \
            "hook_present_in_helper=$(grep -c '_ae_hook H_REQUEST_SCAN_COMPLETE' "$aehome/sessions/$sess/requests" || true)" \
            "hook_fn_present_in_lib=$(grep -c '^_ae_hook ()' "$aehome/sessions/$sess/_lib" || true)"
        # The refreshed helper, hook INACTIVE, must answer byte-for-byte as the pre-refresh
        # helper did on this same fixture, or nothing is captured through it.
        b="$("$aehome/sessions/$sess/requests" all 2>&1)"; rb=$?
        { echo "## refreshed-helper inactive equivalence (D02)"
          echo "pre_refresh_helper_sha256=$(sha "$ACAP/requests.helper.pre-refresh")"
          echo "post_refresh_helper_sha256=$(sha "$ACAP/requests.helper.post-refresh")"
          echo "refresh_rc=$rrc"
          echo "pre_rc=$ra post_rc=$rb"
          echo "identical=$( [[ "$a" == "$b" && "$ra" == "$rb" ]] && echo yes || echo no )"
          echo "--- pre-refresh output ---"; printf '%s\n' "$a"
          echo "--- post-refresh output (hook inactive) ---"; printf '%s\n' "$b"
        } >"$ACAP/helper-refresh-equivalence.txt"
        led helper-refresh-equivalence "identical=$( [[ "$a" == "$b" && "$ra" == "$rb" ]] && echo yes || echo no )" \
            "artifact_sha256=$(sha "$ACAP/helper-refresh-equivalence.txt")"
        [[ "$a" == "$b" && "$ra" == "$rb" ]] || { led HARNESS-ABORT "reason=refreshed helper is not inactive-equivalent"; return 1; }
    fi
    d_snapshot before "$aehome" "$sock"
    d_plain_run "baseline-requests" "$aehome" "$sock" -- "$aehome/sessions/$sess/requests" all
    case "$kind" in
      barrier)
        d_barrier_run H_REQUEST_SCAN_COMPLETE "barrier-requests" "$aehome" "$sock" append_reply \
            -- "$aehome/sessions/$sess/requests" all
        ;;
      twin)
        led twin-note "the identical controller append performed alone so its own effect can be subtracted"
        append_reply "$aehome" "$sock"
        ;;
    esac
    d_snapshot after "$aehome" "$sock"
    # "a clean rerun from the resulting clone" — the same read, unhooked, on the state the
    # barrier arm left behind.
    d_plain_run "clean-rerun-requests" "$aehome" "$sock" -- "$aehome/sessions/$sess/requests" all
    d_trace_run "trace-requests" "$aehome" "$sock" -- "$aehome/sessions/$sess/requests" all
    diff "$ACAP/manifest.before.tsv" "$ACAP/manifest.after.tsv" >"$ACAP/manifest.diff.txt" 2>&1
    { echo "manifest_diff_lines=$(wc -l <"$ACAP/manifest.diff.txt" | tr -d ' ')"
      echo "utc_end=$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"; } >>"$ACAP/case.txt"
    led case-CLOSE "case_txt_sha256=$(sha "$ACAP/case.txt")" "consumers_tsv_sha256=$(sha "$ACAP/consumers.tsv")"
    command tmux -S "$sock" kill-server >/dev/null 2>&1; pkill -x aefake >/dev/null 2>&1
    echo "  $cid ($kind): manifest_diff_lines=$(grep '^manifest_diff_lines=' "$ACAP/case.txt" | cut -d= -f2-)"
}
printf 'd02-requests-vs-reply-writer\tD02,SC-1306d\tD\td02-pending-with-harvested-reply\n' >>"$ADEST/$ARMG/ledger.tsv"
d02_case d02-requests-vs-reply-writer barrier
printf 'd02-controller-only-twin\tD02,SC-1306d\tD\td02-pending-with-harvested-reply\n' >>"$ADEST/$ARMG/ledger.tsv"
d02_case d02-controller-only-twin twin
echo "D02 DONE"
