//! What a session directory holds besides its meta: the helper shims and the
//! workspace manifest.
//!
//! Under the B move every session helper is a THIN SHIM — it names its own
//! session directory and hands the whole argv to the core. The 422-line
//! `sync_session_assets` generator, the `_lib` library it emitted and the
//! `declare -f` template pattern behind both are not ported: there is no longer
//! any helper LOGIC in bash to generate. Helper names and argv are unchanged,
//! which is the compatibility contract that matters — every agent in a live
//! workspace calls them by name.
//!
//! Each artifact is published temp + chmod + rename, the frozen
//! `_publish_executable_artifact` shape: a generator that dies mid-write leaves
//! the previous artifact whole rather than a truncated executable a session
//! would then run.

use std::io;
use std::path::{Path, PathBuf};

/// The helpers whose shim is `exec <core> _<name> <dir> "$@"` — the name on the
/// left is the file, the name on the right is the core entry.
///
/// `peak` is absent: it is an alias for `peek`, and an alias that re-derived
/// its own directory would be a second place the derivation could drift.
pub(crate) const PASSTHROUGH: [(&str, &str); 15] = [
    ("send", crate::cli::SEND),
    ("ask", crate::cli::ASK),
    ("review", crate::cli::REVIEW),
    ("reply", crate::cli::REPLY),
    ("requests", crate::cli::REQUESTS),
    ("state", crate::cli::STATE),
    ("say", crate::cli::SAY),
    ("memo", crate::cli::MEMO),
    ("goal", crate::cli::GOAL),
    ("peek", crate::cli::PEEK),
    ("agents", crate::cli::AGENTS),
    ("focus", crate::cli::FOCUS),
    ("interrupt", crate::cli::INTERRUPT),
    ("spawn", crate::cli::SPAWN),
    ("retire", crate::cli::RETIRE),
];

/// The prologue every generated shim shares.
///
/// `set -euo pipefail` is kept from the frozen helpers even though the body is
/// one `exec`: the directory derivation above it is a command substitution, and
/// a failed `cd` must not reach the core as an empty first argument.
const PROLOGUE: &str = "#!/usr/bin/env bash\n\
     # Generated by ae — do not edit. A session helper is a thin shim: it names\n\
     # its own session directory and hands the whole argv to the ae core.\n\
     set -euo pipefail\n\
     META_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n";

/// Publish one executable artifact: generate to a temp beside the destination,
/// set its mode there, and rename.
///
/// # Errors
///
/// The underlying [`io::Error`] — the write, the mode, or the rename.
fn publish(dest: &Path, body: &str) -> io::Result<()> {
    use std::io::Write as _;
    use std::os::unix::fs::PermissionsExt as _;

    let Some(dir) = dest.parent() else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "an artifact path with no directory",
        ));
    };
    let Some(name) = dest.file_name().and_then(|n| n.to_str()) else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "an artifact path with no name",
        ));
    };
    let temp = dir.join(format!(".{name}.tmp.{}", std::process::id()));
    {
        let mut file = std::fs::File::create(&temp)?;
        file.write_all(body.as_bytes())?;
        file.sync_all()?;
    }
    std::fs::set_permissions(&temp, std::fs::Permissions::from_mode(0o755))?;
    std::fs::rename(&temp, dest)
}

/// Publish a non-executable artifact the same way, mode 0600.
///
/// # Errors
///
/// The underlying [`io::Error`].
pub(crate) fn publish_document(dest: &Path, body: &str) -> io::Result<()> {
    use std::io::Write as _;
    use std::os::unix::fs::PermissionsExt as _;

    let Some(dir) = dest.parent() else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "a document path with no directory",
        ));
    };
    let Some(name) = dest.file_name().and_then(|n| n.to_str()) else {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "a document path with no name",
        ));
    };
    let temp = dir.join(format!(".{name}.tmp.{}", std::process::id()));
    {
        let mut file = std::fs::File::create(&temp)?;
        file.write_all(body.as_bytes())?;
        file.sync_all()?;
    }
    std::fs::set_permissions(&temp, std::fs::Permissions::from_mode(0o600))?;
    std::fs::rename(&temp, dest)
}

/// The shim body for a helper that passes its whole argv through.
#[must_use]
pub(crate) fn passthrough_body(core: &Path, entry: &str) -> String {
    format!(
        "{PROLOGUE}exec {} {entry} \"$META_DIR\" \"$@\"\n",
        crate::launch::shell_quote(&core.display().to_string())
    )
}

/// The shim body for a helper that prepends fixed words — `mark-done`, which is
/// `state done` with the message as its reason.
#[must_use]
fn prefixed_body(core: &Path, entry: &str, words: &[&str]) -> String {
    let mut line = format!(
        "{PROLOGUE}exec {} {entry} \"$META_DIR\"",
        crate::launch::shell_quote(&core.display().to_string())
    );
    for word in words {
        line.push(' ');
        line.push_str(&crate::launch::shell_quote(word));
    }
    line.push_str(" \"$@\"\n");
    line
}

/// The shim body for an alias — one exec to its sibling, so the aliased helper
/// derives the directory exactly once.
#[must_use]
fn alias_body(target: &str) -> String {
    format!(
        "#!/usr/bin/env bash\n\
         # Generated by ae — do not edit. An alias for the '{target}' helper.\n\
         set -euo pipefail\n\
         exec \"$(cd \"$(dirname \"$0\")\" && pwd)/{target}\" \"$@\"\n"
    )
}

/// Write every helper of a session into `dir`, bound to `core`.
///
/// # Errors
///
/// The first artifact that could not be published, with its path — a session
/// missing a helper is not a session, so the caller rolls back rather than
/// starting agents that cannot talk to each other.
pub(crate) fn write_helpers(dir: &Path, core: &Path) -> Result<(), String> {
    let mut artifacts: Vec<(PathBuf, String)> = Vec::new();
    for (name, entry) in PASSTHROUGH {
        artifacts.push((dir.join(name), passthrough_body(core, entry)));
    }
    // `mark-done` is the shorthand the watchdog and the workspace manifest both
    // still name; it is `state done` with the message as the reason.
    artifacts.push((
        dir.join("mark-done"),
        prefixed_body(core, crate::cli::STATE, &["done"]),
    ));
    artifacts.push((dir.join("peak"), alias_body("peek")));
    // The two MONITOR panes' processes. Each is the pane's whole command, so it
    // must be an executable file: tmux runs it, not a shell that could expand a
    // core path with spaces in it.
    artifacts.push((
        dir.join("watchdog"),
        passthrough_body(core, crate::cli::WATCHDOG_RUN),
    ));
    artifacts.push((
        dir.join("events-tail"),
        passthrough_body(core, crate::cli::EVENTS_TAIL),
    ));
    // `loop` is the deprecated spelling of the watchdog helper, kept as an
    // alias so a session created before the rename keeps working.
    artifacts.push((dir.join("loop"), alias_body("watchdog")));

    for (path, body) in artifacts {
        publish(&path, &body)
            .map_err(|why| format!("could not write {} ({why})", path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
#[allow(
    clippy::disallowed_methods,
    reason = "tests read back what the door wrote; the boundary is on product code — see clippy.toml"
)]
mod tests {
    use super::*;

    #[test]
    fn a_passthrough_shim_execs_the_core_with_the_whole_argv() {
        let body = passthrough_body(Path::new("/opt/ae core"), "_send");
        assert!(body.starts_with("#!/usr/bin/env bash\n"));
        assert!(
            body.ends_with("exec '/opt/ae core' _send \"$META_DIR\" \"$@\"\n"),
            "{body}"
        );
    }

    #[test]
    fn mark_done_is_state_done_with_the_rest_as_the_reason() {
        let body = prefixed_body(Path::new("/c"), "_state", &["done"]);
        assert!(
            body.ends_with("exec '/c' _state \"$META_DIR\" 'done' \"$@\"\n"),
            "{body}"
        );
    }

    #[test]
    fn an_alias_execs_its_sibling_not_the_core() {
        let body = alias_body("peek");
        assert!(body.contains("/peek\" \"$@\"\n"), "{body}");
        assert!(
            !body.contains("META_DIR"),
            "an alias derives nothing itself"
        );
    }

    #[test]
    fn every_named_helper_is_published() {
        use std::os::unix::fs::PermissionsExt as _;
        let dir = tempdir();
        write_helpers(&dir, Path::new("/c")).unwrap();
        for name in [
            "send",
            "ask",
            "review",
            "reply",
            "requests",
            "state",
            "mark-done",
            "say",
            "memo",
            "goal",
            "peek",
            "peak",
            "agents",
            "focus",
            "interrupt",
            "spawn",
            "retire",
            "loop",
            "watchdog",
            "events-tail",
        ] {
            let path = dir.join(name);
            let meta = std::fs::metadata(&path)
                .unwrap_or_else(|why| panic!("{name} was not published ({why})"));
            assert_eq!(meta.permissions().mode() & 0o777, 0o755, "{name}");
        }
    }

    fn tempdir() -> PathBuf {
        let base = std::env::temp_dir().join(format!(
            "ae-assets-{}-{}",
            std::process::id(),
            crate::launch::generate_uuid()
        ));
        std::fs::create_dir_all(&base).unwrap();
        base
    }
}
