#!/opt/homebrew/bin/bash
# T-100 observation tables — GENERATED FROM THE ARM ARTIFACTS.
# Every value is read out of an ARM.txt, ledger.tsv, hash-timeline.txt or
# watchdog-verdict-lines.txt. Nothing here is typed by hand, and no value in the
# report may exist that this script cannot produce.
set -uo pipefail
A="${1:-/Users/ckriech/projects/clemens33/ae-rust/docs/migration/evidence/t-artifacts/T-100}"
f_of() { grep -m1 "^$2" "$1" 2>/dev/null | cut -f2; }
led_of() { grep -m1 "$2" "$1" 2>/dev/null | awk -F'\t' '{print $NF}'; }
h_of() { local v; v="$(grep -m1 "^$2" "$1" 2>/dev/null | cut -f2 | cut -c1-8)"; printf '%s' "${v:--}"; }

printf '# T-100 observation tables — GENERATED by _harness/t100-mktables.sh from the\n'
printf '# arm artifacts. CAPTURE ONLY: no value here is a verdict.\n\n'

printf '## TABLE 1 — nudges, per arm\n'
printf '%-24s %-13s %-7s %-15s %-11s %-11s %-12s %s\n' ARM STATE SOURCE nudges_at_decl nudges_end after_decl wrote_cycle ARM_INVALID
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; f="$d/ARM.txt"; [[ -f "$f" ]] || continue
  printf '%-24s %-13s %-7s %-15s %-11s %-11s %-12s %s\n' "$n" \
    "$(f_of "$f" quiet_state)" "$(f_of "$f" change_source)" \
    "$(f_of "$f" nudges_at_declaration)" "$(f_of "$f" nudges_total_at_end)" \
    "$(f_of "$f" nudges_after_declaration)" "$(f_of "$f" wrote_at_cycle)" \
    "$( [[ -f "$d/ARM-INVALID.txt" ]] && echo YES || echo no )"
done

printf '\n## TABLE 2 — the instrument live control, and the declaration\n'
printf '%-24s %-24s %-25s %-10s %s\n' ARM plain_write_registered nudge_shaped_registered state_rc nudge_seen_first
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; f="$d/ARM.txt"; l="$d/ledger.tsv"; [[ -f "$f" ]] || continue
  printf '%-24s %-24s %-25s %-10s %s\n' "$n" \
    "$(led_of "$l" 'plain-write.registered')" "$(led_of "$l" 'nudge-shaped.registered')" \
    "$(f_of "$f" state_helper_rc)" "$(f_of "$f" nudge_observed_before_write)"
done

printf '\n## TABLE 3 — the FROZEN scrubbed hash at the named observation points (first 8 chars)\n'
printf '##           equal values mean the scrubber saw no change between those points\n'
printf '%-24s %-12s %-13s %-15s %-10s\n' ARM t0_pre_decl t1_post_decl t2_after_write t3_final
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; h="$d/hash-timeline.txt"; [[ -f "$h" ]] || continue
  printf '%-24s %-12s %-13s %-15s %-10s\n' "$n" \
    "$(h_of "$h" t0-pre)" "$(h_of "$h" t1-post)" "$(h_of "$h" t2-after)" "$(h_of "$h" t3-final)"
done

printf '\n## TABLE 4 — the watchdog OWN per-cycle verdict CLASSES for the observed agent,\n'
printf '##           in first-appearance order with occurrence counts (seconds normalised)\n'
for d in "$A"/arms/*/; do
  n="$(basename "$d")"; w="$d/watchdog-verdict-lines.txt"; [[ -f "$w" ]] || continue
  printf '%s\n' "$n"
  grep -v '^#' "$w" 2>/dev/null \
    | sed 's/^\[[0-9:]*\] *//; s/^[^ ]*  *//' \
    | sed 's/([0-9]*s ago)/(Ns ago)/; s/(idle [0-9]*m)/(idle Nm)/; s|([0-9]*/[0-9]*)|(n/m)|g; s/rc=[0-9]*/rc=N/' \
    | awk '{c[$0]++; if(!($0 in o)){o[$0]=++k; ord[k]=$0}} END{for(i=1;i<=k;i++) printf "    %3d x  %s\n", c[ord[i]], ord[i]}'
done
